Description: Main stack

Parameters:

  DeployEnv:
    Description: Deploy environment name; just testing
    Type: String
    AllowedValues:
      - test
      - stage
      - production

  LambdaFunctionName:
    Description: The name of the Lambda function
    Type: String
    MinLength: 1 # required

  LambdaCodeS3BucketName:
    Description: S3 bucket where the Lambda function code is to live
    Type: String
    MinLength: 1 # required

Resources:

  TestLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Description: The role assumed by the Lambda function to get access to resources that it needs.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'

  TestLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Ref: LambdaFunctionName
      Description: Just a test Lambda function.
      Handler: index.handler
      MemorySize: 256
      Timeout: 60
      Role: !GetAtt TestLambdaRole.Arn
      Runtime: nodejs10.x
      Code:
        # ZipFile: |
        #   def handler(event, context):
        #     response = {
        #       'isBase64Encoded': False,
        #       'statusCode': 200,
        #       'headers': {},
        #       'multiValueHeaders': {},
        #       'body': 'Hello, World!'
        #     }
        #     return response
        S3Bucket:
          Ref: LambdaCodeS3BucketName
        S3Key: test-lambda.zip

  TestLambdaExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt TestLambdaFunction.Arn
      Principal: apigateway.amazonaws.com

  TestLambdaApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: test-lambda-api-endpoint
      ApiKeySourceType: HEADER
      EndpointConfiguration:
        Types:
          - EDGE

  TestLambdaApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: TestLambdaApiMethod1
    Properties:
      RestApiId: !Ref TestLambdaApi

  TestLambdaApiProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TestLambdaApi
      ParentId: !GetAtt TestLambdaApi.RootResourceId
      PathPart: 'lambda'

  TestLambdaApiMethod1:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref TestLambdaApi
      ResourceId: !Ref TestLambdaApiProxyResource
      AuthorizationType: NONE # https://docs.aws.amazon.com/apigateway/api-reference/resource/method/#authorizationType
      ApiKeyRequired: false
      HttpMethod: POST
      Integration:
        ConnectionType: INTERNET
        Credentials: !GetAtt TestLambdaExecutionRole.Arn
        IntegrationHttpMethod: POST
        PassthroughBehavior: WHEN_NO_MATCH
        Type: AWS_PROXY # https://docs.aws.amazon.com/apigateway/api-reference/resource/integration/#type
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TestLambdaFunction.Arn}/invocations"

  TestLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: 'Allow'
            Principal:
              Service:
                - 'apigateway.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: LambdaAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'lambda:*'
                Resource: !GetAtt TestLambdaFunction.Arn

  ApiGatewayModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: 'application/json'
      RestApiId: !Ref TestLambdaApi
      Schema: {}

  TestLambdaApiStage:
    DependsOn: TestLambdaApiDeployment
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref TestLambdaApi
      DeploymentId: !Ref TestLambdaApiDeployment
      StageName: test
