Description: My test cloud formation

Parameters:

  DeployEnv:
    Description: Deploy environment name; just testing
    Type: String
    AllowedValues:
      - stage
      - production

  LambdaFunctionName:
    Description: The name of the Lambda function
    Type: String
    MinLength: 1 # TODO: How do I properly declare it required?

  LambdaCodeS3Bucket:
    Description: S3 bucket where the Lambda function code is to live
    Type: String
    MinLength: 1 # TODO: How do I properly declare it required?

Resources:

  TestLambdaS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: LambdaCodeS3Bucket
      VersioningConfiguration:
        Status: Enabled
      AccessControl: PublicRead

  TestLambdaApiEndpoint:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: test-lambda-api-endpoint
      Description: Just checking

  TestLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Ref: LambdaFunctionName
      Description: Just a test Lambda function.
      Handler: index.handler
      Role: arn:aws:iam::750527397320:role/service-role/test-lambda-role-p619ela7
      Runtime: nodejs10.x
      Code:
        S3Bucket: gurdiga-lambda-code
        S3Key: test-lambda.zip

  TestLambdaExecuterRole:
    Type: AWS::IAM::Role
    Properties:
      Description: A role to use with Lambda functions
      AssumeRolePolicyDocument:
        Statement:
          -
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
